import html
import re
import tempfile
import os
from fpdf import FPDF
from datetime import datetime


def generate_pdf_report(
    image_bytes, prediction, accuracy, recommendation, heatmap_bytes=None
):
    """Generate a medical-style PDF report for the skin analysis."""

    # 1. Setup PDF
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # 2. Header (Professional Branding)
    pdf.set_font("helvetica", "B", 24)
    pdf.set_text_color(44, 62, 80)  # Dark Blue/Grey
    pdf.cell(0, 15, "Skin Analysis Report", ln=True, align="C")

    pdf.set_font("helvetica", "I", 10)
    pdf.set_text_color(127, 140, 141)  # Grey
    pdf.cell(
        0,
        10,
        f"Generated by SkinCare AI on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        ln=True,
        align="C",
    )
    pdf.ln(5)

    # 3. Images Section (Side-by-Side)
    if heatmap_bytes:
        f1_path = None
        f2_path = None
        try:
            with (
                tempfile.NamedTemporaryFile(delete=False, suffix=".jpg") as f1,
                tempfile.NamedTemporaryFile(delete=False, suffix=".jpg") as f2,
            ):
                f1.write(image_bytes)
                f2.write(heatmap_bytes)
                f1_path = f1.name
                f2_path = f2.name

            # Add images
            img_w = 85
            current_y = pdf.get_y()
            pdf.image(f1_path, x=15, y=current_y, w=img_w)
            pdf.image(f2_path, x=110, y=current_y, w=img_w)

            pdf.set_y(current_y + 90)  # Adjust Y after images

            # Labels for images
            pdf.set_font("helvetica", "B", 9)
            pdf.set_text_color(100, 100, 100)
            pdf.set_xy(15, current_y + 86)
            pdf.cell(img_w, 5, "Original Scan", align="C")
            pdf.set_xy(110, current_y + 86)
            pdf.cell(img_w, 5, "(Heatmap)", align="C")
            pdf.ln(10)
        finally:
            if f1_path and os.path.exists(f1_path):
                os.unlink(f1_path)
            if f2_path and os.path.exists(f2_path):
                os.unlink(f2_path)

    # 4. Results Summary Box
    pdf.set_fill_color(236, 240, 241)
    pdf.set_draw_color(44, 62, 80)
    pdf.set_line_width(0.5)

    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 12, f"  Condition Detected: {prediction}", border=1, ln=True, fill=True)

    pdf.set_font("helvetica", "", 12)
    pdf.cell(0, 10, f"  Confidence Score: {accuracy:.2%}", border=1, ln=True)
    pdf.ln(8)

    # 5. AI Advisor Recommendations (Markdown to HTML)
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(41, 128, 185)  # Medical Blue
    pdf.cell(0, 10, "AI Advisor Recommendations", ln=True)
    pdf.set_line_width(0.2)
    pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 190, pdf.get_y())
    pdf.ln(5)

    clean_recommendation = (
        recommendation.replace("•", "- ").replace("—", "-").replace("–", "-")
    )
    clean_recommendation = (
        clean_recommendation.replace("“", '"')
        .replace("”", '"')
        .replace("‘", "'")
        .replace("’", "'")
    )

    # Convert Markdown to basic HTML for fpdf2

    html_content = html.escape(clean_recommendation)

    html_content = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", html_content)

    # Headers
    html_content = re.sub(
        r"^### (.*)$", r"<br><b>\1</b><br>", html_content, flags=re.MULTILINE
    )
    html_content = re.sub(
        r"^## (.*)$", r"<br><b>\1</b><br>", html_content, flags=re.MULTILINE
    )

    html_content = re.sub(r"^[-\*] (.*)$", r" - \1", html_content, flags=re.MULTILINE)

    # Newlines
    html_content = html_content.replace("\n", "<br>")

    html_content = (
        html_content.encode("latin-1", "replace").decode("latin-1").replace("?", " ")
    )

    pdf.set_font("helvetica", size=11)
    pdf.set_text_color(0, 0, 0)
    pdf.write_html(f'<font face="helvetica" size="11">{html_content}</font>')

    # 6. Footer Disclaimer
    pdf.ln(20)
    pdf.set_font("helvetica", "I", 8)
    pdf.set_text_color(149, 165, 166)
    disclaimer = "DISCLAIMER: This report is generated by an Artificial Intelligence system for informational purposes only. It is NOT a professional medical diagnosis. Please consult a board-certified dermatologist for any clinical evaluation or treatment."
    pdf.multi_cell(0, 5, disclaimer, align="C")

    return pdf.output()
