from pathlib import Path
from sqlalchemy import func
from core.dependency import SessionLocal
from models.db_models import SkinAnalysisLog

from fpdf import FPDF
from datetime import datetime

def generate_pdf_report(image_bytes, prediction, accuracy, recommendation):
    """Generate a medical-style PDF report for the skin analysis."""
    pdf = FPDF()
    pdf.add_page()
    
    # 1. Header
    pdf.set_font("Arial", 'B', 20)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 15, "Skin Disease Analysis Report", ln=True, align='C')
    pdf.set_font("Arial", size=10)
    pdf.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align='C')
    pdf.ln(10)
    
    # 2. Prediction Box
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, f"Detected Condition: {prediction}", border=1, ln=True, fill=True)
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, f"Confidence Score: {accuracy:.2%}", border=1, ln=True)
    pdf.ln(10)
    
    # 3. Recommendation Section
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "AI Advisor Recommendations:", ln=True)
    pdf.set_font("Arial", size=11)
    
    # Clean recommendation text (fpdf doesn't like some markdown characters)
    clean_text = recommendation.replace("**", "").replace("#", "").replace("- ", " - ").replace("•", "-")
    pdf.multi_cell(0, 8, clean_text)
    
    # 4. Footer Disclaimer
    pdf.ln(15)
    pdf.set_font("Arial", 'I', 8)
    pdf.set_text_color(150, 150, 150)
    disclaimer = "This report is generated by an AI system. It is NOT a professional medical diagnosis. Please consult a certified dermatologist for any skin concerns."
    pdf.multi_cell(0, 5, disclaimer, align='C')
    
    return pdf.output()

def list_local_models():
    """List .pt models directly from the filesystem."""
    model_dir = Path("models/weights")
    if not model_dir.exists():
        return []
    return [f.name for f in model_dir.glob("*.pt")]

def get_local_stats():
    """Get disease statistics directly from the database."""
    db = SessionLocal()
    try:
        stats = db.query(SkinAnalysisLog.prediction, func.count(SkinAnalysisLog.id)).group_by(SkinAnalysisLog.prediction).all()
        return {item[0]: item[1] for item in stats}
    except Exception:
        return {}
    finally:
        db.close()
